[app]
name = "RepClient"
description = "Official cli client of repproject"

[api]
host = "https://repproject.world"
api_key = "@repproject"

[output]
# supported appended-style formats: "txt", "ndjson"
# another format: "json", "csv"
format = "txt"
dir = "output"

[log]
# supported log levels: "trace", "debug", "info", "warn", "error", "fatal"
level = "debug"

[[log.stdout]]
format = "text"
output = "stdout"

[[log.file]]
format = "json"
path = "log/app.log"
max_size = 10     # in MB, depends on how you implement log rotation
max_age = 7       # in days%