name: Notify Telegram

on:
  push:
    branches:
      - main  # or your default branch
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            TEXT="🚀 New commit to *${{ github.repository }}*
            
            *Message:* ${{ github.event.head_commit.message }}
            
            [View Commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})"
          elif [[ "${{ github.event_name }}" == "release" ]]; then
            TEXT="🎉 New *release* published: *${{ github.event.release.name }}*
            
            [View Release](${{ github.event.release.html_url }})"
          fi

          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d parse_mode=Markdown \
            -d text="$TEXT"
