name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger only on tag push like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64]

    name: Build ${{ matrix.goos }}-${{ matrix.goarch }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # adjust if needed

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p dist
          output_name="repclient-${GOOS}-${GOARCH}"
          if [ "$GOOS" == "windows" ]; then
            output_name="${output_name}.exe"
          fi
          go build -o "dist/${output_name}" ./cmd/main.go

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
